/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as GamificationRouteImport } from './routes/gamification'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ChallengeIdRouteImport } from './routes/challenge.$id'
import { Route as ConversationIndexRouteImport } from './routes/conversation.$index'
import { Route as LoyaltyIndexRouteImport } from './routes/loyalty.index'
import { Route as LoyaltyHistoryRouteImport } from './routes/loyalty.history'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'
import { Route as PointsIndexRouteImport } from './routes/points.index'
import { Route as PointsConvertRouteImport } from './routes/points.convert'
import { Route as PointsExpiryRouteImport } from './routes/points.expiry'
import { Route as PointsHistoryRouteImport } from './routes/points.history'
import { Route as PointsMarketplaceRouteImport } from './routes/points.marketplace'
import { Route as RewardIdRouteImport } from './routes/reward.$id'
import { Route as SpinHistoryRouteImport } from './routes/spin.history'
import { Route as TicketIndexRouteImport } from './routes/ticket.$index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const GamificationRoute = GamificationRouteImport.update({
  id: '/gamification',
  path: '/gamification',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeIdRoute = ChallengeIdRouteImport.update({
  id: '/challenge/$id',
  path: '/challenge/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationIndexRoute = ConversationIndexRouteImport.update({
  id: '/conversation/$index',
  path: '/conversation/$index',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyIndexRoute = LoyaltyIndexRouteImport.update({
  id: '/loyalty/',
  path: '/loyalty/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyHistoryRoute = LoyaltyHistoryRouteImport.update({
  id: '/loyalty/history',
  path: '/loyalty/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/marketplace/$id',
  path: '/marketplace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsIndexRoute = PointsIndexRouteImport.update({
  id: '/points/',
  path: '/points/',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsConvertRoute = PointsConvertRouteImport.update({
  id: '/points/convert',
  path: '/points/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsExpiryRoute = PointsExpiryRouteImport.update({
  id: '/points/expiry',
  path: '/points/expiry',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsHistoryRoute = PointsHistoryRouteImport.update({
  id: '/points/history',
  path: '/points/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsMarketplaceRoute = PointsMarketplaceRouteImport.update({
  id: '/points/marketplace',
  path: '/points/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardIdRoute = RewardIdRouteImport.update({
  id: '/reward/$id',
  path: '/reward/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SpinHistoryRoute = SpinHistoryRouteImport.update({
  id: '/spin/history',
  path: '/spin/history',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketIndexRoute = TicketIndexRouteImport.update({
  id: '/ticket/$index',
  path: '/ticket/$index',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/challenges': typeof ChallengesRoute
  '/gamification': typeof GamificationRoute
  '/notifications': typeof NotificationsRoute
  '/rewards': typeof RewardsRoute
  '/challenge/$id': typeof ChallengeIdRoute
  '/conversation/$index': typeof ConversationIndexRoute
  '/loyalty/history': typeof LoyaltyHistoryRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/points/convert': typeof PointsConvertRoute
  '/points/expiry': typeof PointsExpiryRoute
  '/points/history': typeof PointsHistoryRoute
  '/points/marketplace': typeof PointsMarketplaceRoute
  '/reward/$id': typeof RewardIdRoute
  '/spin/history': typeof SpinHistoryRoute
  '/ticket/$index': typeof TicketIndexRoute
  '/loyalty/': typeof LoyaltyIndexRoute
  '/points/': typeof PointsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/challenges': typeof ChallengesRoute
  '/gamification': typeof GamificationRoute
  '/notifications': typeof NotificationsRoute
  '/rewards': typeof RewardsRoute
  '/challenge/$id': typeof ChallengeIdRoute
  '/conversation/$index': typeof ConversationIndexRoute
  '/loyalty/history': typeof LoyaltyHistoryRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/points/convert': typeof PointsConvertRoute
  '/points/expiry': typeof PointsExpiryRoute
  '/points/history': typeof PointsHistoryRoute
  '/points/marketplace': typeof PointsMarketplaceRoute
  '/reward/$id': typeof RewardIdRoute
  '/spin/history': typeof SpinHistoryRoute
  '/ticket/$index': typeof TicketIndexRoute
  '/loyalty': typeof LoyaltyIndexRoute
  '/points': typeof PointsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/challenges': typeof ChallengesRoute
  '/gamification': typeof GamificationRoute
  '/notifications': typeof NotificationsRoute
  '/rewards': typeof RewardsRoute
  '/challenge/$id': typeof ChallengeIdRoute
  '/conversation/$index': typeof ConversationIndexRoute
  '/loyalty/history': typeof LoyaltyHistoryRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/points/convert': typeof PointsConvertRoute
  '/points/expiry': typeof PointsExpiryRoute
  '/points/history': typeof PointsHistoryRoute
  '/points/marketplace': typeof PointsMarketplaceRoute
  '/reward/$id': typeof RewardIdRoute
  '/spin/history': typeof SpinHistoryRoute
  '/ticket/$index': typeof TicketIndexRoute
  '/loyalty/': typeof LoyaltyIndexRoute
  '/points/': typeof PointsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/badges'
    | '/challenges'
    | '/gamification'
    | '/notifications'
    | '/rewards'
    | '/challenge/$id'
    | '/conversation/$index'
    | '/loyalty/history'
    | '/marketplace/$id'
    | '/points/convert'
    | '/points/expiry'
    | '/points/history'
    | '/points/marketplace'
    | '/reward/$id'
    | '/spin/history'
    | '/ticket/$index'
    | '/loyalty/'
    | '/points/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/badges'
    | '/challenges'
    | '/gamification'
    | '/notifications'
    | '/rewards'
    | '/challenge/$id'
    | '/conversation/$index'
    | '/loyalty/history'
    | '/marketplace/$id'
    | '/points/convert'
    | '/points/expiry'
    | '/points/history'
    | '/points/marketplace'
    | '/reward/$id'
    | '/spin/history'
    | '/ticket/$index'
    | '/loyalty'
    | '/points'
  id:
    | '__root__'
    | '/'
    | '/badges'
    | '/challenges'
    | '/gamification'
    | '/notifications'
    | '/rewards'
    | '/challenge/$id'
    | '/conversation/$index'
    | '/loyalty/history'
    | '/marketplace/$id'
    | '/points/convert'
    | '/points/expiry'
    | '/points/history'
    | '/points/marketplace'
    | '/reward/$id'
    | '/spin/history'
    | '/ticket/$index'
    | '/loyalty/'
    | '/points/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BadgesRoute: typeof BadgesRoute
  ChallengesRoute: typeof ChallengesRoute
  GamificationRoute: typeof GamificationRoute
  NotificationsRoute: typeof NotificationsRoute
  RewardsRoute: typeof RewardsRoute
  ChallengeIdRoute: typeof ChallengeIdRoute
  ConversationIndexRoute: typeof ConversationIndexRoute
  LoyaltyHistoryRoute: typeof LoyaltyHistoryRoute
  MarketplaceIdRoute: typeof MarketplaceIdRoute
  PointsConvertRoute: typeof PointsConvertRoute
  PointsExpiryRoute: typeof PointsExpiryRoute
  PointsHistoryRoute: typeof PointsHistoryRoute
  PointsMarketplaceRoute: typeof PointsMarketplaceRoute
  RewardIdRoute: typeof RewardIdRoute
  SpinHistoryRoute: typeof SpinHistoryRoute
  TicketIndexRoute: typeof TicketIndexRoute
  LoyaltyIndexRoute: typeof LoyaltyIndexRoute
  PointsIndexRoute: typeof PointsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamification': {
      id: '/gamification'
      path: '/gamification'
      fullPath: '/gamification'
      preLoaderRoute: typeof GamificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/$id': {
      id: '/challenge/$id'
      path: '/challenge/$id'
      fullPath: '/challenge/$id'
      preLoaderRoute: typeof ChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation/$index': {
      id: '/conversation/$index'
      path: '/conversation/$index'
      fullPath: '/conversation/$index'
      preLoaderRoute: typeof ConversationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty/': {
      id: '/loyalty/'
      path: '/loyalty'
      fullPath: '/loyalty/'
      preLoaderRoute: typeof LoyaltyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty/history': {
      id: '/loyalty/history'
      path: '/loyalty/history'
      fullPath: '/loyalty/history'
      preLoaderRoute: typeof LoyaltyHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/marketplace/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points/': {
      id: '/points/'
      path: '/points'
      fullPath: '/points/'
      preLoaderRoute: typeof PointsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points/convert': {
      id: '/points/convert'
      path: '/points/convert'
      fullPath: '/points/convert'
      preLoaderRoute: typeof PointsConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points/expiry': {
      id: '/points/expiry'
      path: '/points/expiry'
      fullPath: '/points/expiry'
      preLoaderRoute: typeof PointsExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points/history': {
      id: '/points/history'
      path: '/points/history'
      fullPath: '/points/history'
      preLoaderRoute: typeof PointsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points/marketplace': {
      id: '/points/marketplace'
      path: '/points/marketplace'
      fullPath: '/points/marketplace'
      preLoaderRoute: typeof PointsMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reward/$id': {
      id: '/reward/$id'
      path: '/reward/$id'
      fullPath: '/reward/$id'
      preLoaderRoute: typeof RewardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spin/history': {
      id: '/spin/history'
      path: '/spin/history'
      fullPath: '/spin/history'
      preLoaderRoute: typeof SpinHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$index': {
      id: '/ticket/$index'
      path: '/ticket/$index'
      fullPath: '/ticket/$index'
      preLoaderRoute: typeof TicketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BadgesRoute: BadgesRoute,
  ChallengesRoute: ChallengesRoute,
  GamificationRoute: GamificationRoute,
  NotificationsRoute: NotificationsRoute,
  RewardsRoute: RewardsRoute,
  ChallengeIdRoute: ChallengeIdRoute,
  ConversationIndexRoute: ConversationIndexRoute,
  LoyaltyHistoryRoute: LoyaltyHistoryRoute,
  MarketplaceIdRoute: MarketplaceIdRoute,
  PointsConvertRoute: PointsConvertRoute,
  PointsExpiryRoute: PointsExpiryRoute,
  PointsHistoryRoute: PointsHistoryRoute,
  PointsMarketplaceRoute: PointsMarketplaceRoute,
  RewardIdRoute: RewardIdRoute,
  SpinHistoryRoute: SpinHistoryRoute,
  TicketIndexRoute: TicketIndexRoute,
  LoyaltyIndexRoute: LoyaltyIndexRoute,
  PointsIndexRoute: PointsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
